# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'
target 'iOSDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSDemo
  pod 'ColorCubeSwift', :path => "../"

  target 'iOSDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
